backend:
  name: github
  repo: spaceface42/_blackhole
  branch: main

media_folder: "uploads"
public_folder: "/_blackhole/uploads"

collections:
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"